### ISSUE TITLE
KEY and KEYREF

### ISSUE THREAD

**Issue by syrenio** [syrenio/XMLText#11]
Es gibt schlüssel attribute und keyrefs in XML Schemas. das ist super - wie in den datenbanken - da gibt es zusammnegesetzte Primary Keys und zusammengesetze Foreign Keys

There is an important distinction to be made between ID/IDREF and KEY/KEYREF. While the former does not oppose any restrictions on the type to be referenced, the latter does. 

Therefore, after discussions, we thought that one could introduce:
- CommonType to be specified by any ID and referenced by any IDREF
- ACTUAL_TYPE to be specified by any KEY and referenced by any KEYREF

**Comment by dirmhirn** [comment]
http://docstore.mik.ua/orelly/xml/schema/ch09_03.htm
https://github.com/patrickneubauer/XMLText/blob/master/INDIVIDUAL%20EXPERIMENTS/SandboxProject/metamodels/Example_with_key.xsd

http://www.w3.org/TR/xmlschema-1/#cIdentity-constraint_Definitions

•(unique) the Identity-constraint definition asserts uniqueness, with respect to the content identified by {selector}, of the tuples resulting from evaluation of the {fields} XPath expression(s). 
•(key) the Identity-constraint definition asserts uniqueness as for unique. key further asserts that all selected content actually has such tuples.
•(keyref) the Identity-constraint definition asserts a correspondence, with respect to the content identified by {selector}, of the tuples resulting from evaluation of the {fields} XPath expression(s), with those of the {referenced key}. 
•The comparison between keyref {fields} and key or unique {fields} is by value equality, not by string equality. (in contrast to ID/IDREF)

key -> required Attribute equal to  use="required" 

use="required" -> Ecore property [1] ok
xsd:key -> OCL invariant uniqueAttribute: XPathSelector.allInstances()->isUnique(KEY-name); ?

search in ecore for key-selector -> path to xsd:key container in ecore
--> invariant self.[xsd:key Container]. ... .[key-selector]->forAll(c1, c2 | c1 <> c2 implies c1.[key-fields] <> c2.[key-fields]) ??

ID/IDREF
xsd:id -> just ecore {unique} ?
